In [1]:
# Abstraction:   Hiding the implementational details of a class and showing only the essential features to the user
# Encapsulation: Wrapping data and functions into a single unit(object). Basically it is data + method

class Car:
  def __init__(self, number):
    self.acc = False
    self.clutch = False
    self.brake = False
    self.carNumber = number
  def startCar(self):
    self.clutch = True
    self.acc = True
    print(f"In car {self.carNumber}, clutch turned {self.clutch} and accelerator turned {self.acc} so start the car")
  def stopCar(self):
    self.brake = True
    self.acc = False
    print(f"In car {self.carNumber}, Brake turned {self.brake} and accelerator turned {self.acc} so stop the car")

car1 = Car(1)
car2 = Car(2)

car1.startCar()
car2.startCar()

car1.stopCar()
car2.stopCar()

In car 1, clutch turned True and accelerator turned True so start the car
In car 2, clutch turned True and accelerator turned True so start the car
In car 1, Brake turned True and accelerator turned False so stop the car
In car 2, Brake turned True and accelerator turned False so stop the car

In [2]:
# Inheritance:

class Employee: # Parent class
  def __init__(self, name, id):
    self.name = name
    self.id = id

  def showEmployeeDetails(self):
    print(f"The name of employee {self.id} is {self.name} ")

class Programmer(Employee): # child class
  def showLanguage(self, lang):
    print(f"The Programmer {self.name} works using {lang}")

# e1 = Employee("Archit", 101)
# e1.showEmployeeDetails()

p1 = Programmer("Bipasha", 102)
p1.showEmployeeDetails()
p1.showLanguage("Java")

The name of employee 102 is Bipasha
The Programmer Bipasha works using Java

In [3]:
class A:
  def feature1(self):
    print("This is feature 1 of class A")
  def feature2(self):
    print("This is feature 2 of class A")

class B(A): # single-level inheritance
  def feature3(self):
    print("This is feature 3 of class B")
  def feature4(self):
    print("This is feature 4 of class B")

class C(B): # multi-level inheritance
  def feature5(self):
    print("This is feature 5 of class C")
  def feature6(self):
    print("This is feature 6 of class C")

if __name__ == "__main__":
  a = A()
  b = B()
  c = C()

  print(f"{"*"*40}Using class A{"*"*40}")
  a.feature1()
  a.feature2()

  print(f"{"*"*40}Using class B{"*"*40}")
  b.feature1()
  b.feature2()
  b.feature3()
  b.feature4()

  print(f"{"*"*40}Using class C{"*"*40}")
  c.feature5()
  c.feature4()
  c.feature1()

****************************************Using class A****************************************
This is feature 1 of class A
This is feature 2 of class A
****************************************Using class B****************************************
This is feature 1 of class A
This is feature 2 of class A
This is feature 3 of class B
This is feature 4 of class B
****************************************Using class C****************************************
This is feature 5 of class C
This is feature 4 of class B
This is feature 1 of class A

In [4]:
"""
Why use Numpy ?
Numpy provides a more efficient storage compared to the other data structures. It uses less memory to store data
It performs fast mathematical operations
"""

import numpy as np
myArr = np.array([1,2.87,'IDEAS-TIH'])
print(myArr, type(myArr))
print(myArr[2])
print(myArr.dtype)

myArr_new = np.array([1,2.87,60,8.765432 ], np.int32)
print(myArr_new, type(myArr_new), myArr_new.dtype)
print(f"The shape of the array = {myArr_new.shape}")

['1' '2.87' 'IDEAS-TIH'] <class 'numpy.ndarray'>
IDEAS-TIH
<U32
[ 1  2 60  8] <class 'numpy.ndarray'> int32
The shape of the array = (4,)

In [5]:
myArr_2D=np.array([[3,4,5,6],[7,6,5,4]])
print(myArr_2D, type(myArr_2D), myArr_2D.dtype)
print(f"The shape of the array = {myArr_2D.shape}")

[[3 4 5 6]
 [7 6 5 4]] <class 'numpy.ndarray'> int64
The shape of the array = (2, 4)

In [6]:
# Array Creation : Conversion from other python data structures, namely lists
myList = [[1, 'harry', 3,8],[5,85,7,8],[9.67, 2, 125.578, 8, ]]
listArray = np.array(myList) # converting lists to arrays explicitly
print(listArray, type(listArray), listArray.dtype)
print(listArray.shape[0])
print(listArray.shape[1])
print(listArray.size)
print(listArray[2,1])

[['1' 'harry' '3' '8']
 ['5' '85' '7' '8']
 ['9.67' '2' '125.578' '8']] <class 'numpy.ndarray'> <U32
3
4
12
2

In [7]:
zero_arrays = np.zeros((2,5))
print(zero_arrays, type(zero_arrays), zero_arrays.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] <class 'numpy.ndarray'> float64

In [8]:
rng = np.arange(15) # arange(x) generates an array of length x having elements from 0 to x-1
print(rng, rng.shape)
print("*"*80)
reshape_rng = rng.reshape(3,5)
print(reshape_rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] (15,)
********************************************************************************
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

In [9]:
lspace = np.linspace(1,5, 10) # linspace(x,y,z) : returns an array of length z that has z equally spaced numbers from x to y
print(lspace)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]

In [10]:
# empty arrays:
empArr = np.empty((4,6)) # CREATE A 4X6 EMPTY MATRIX
print(empArr, type(empArr), empArr.dtype)

[[-0.25 -0.5   0.   -0.25  0.25 -0.5 ]
 [ 0.5  -0.25  0.25  0.    0.5   0.25]
 [ 0.25  0.5   0.    0.25 -0.25  0.5 ]
 [-0.5   0.25 -0.25  0.   -0.5  -0.25]] <class 'numpy.ndarray'> float64

In [11]:
empArr_like = np.empty_like(zero_arrays)
print(empArr_like, empArr_like.shape)

[[1.         1.44444444 1.88888889 2.33333333 2.77777778]
 [3.22222222 3.66666667 4.11111111 4.55555556 5.        ]] (2, 5)

In [12]:
ide = np.identity(5)
print(ide, ide.size, ide.shape)
print(np.linalg.det(ide)) # linalg.det()is used to calculate the determinant of a matrix

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 25 (5, 5)
1.0

In [13]:
'''
1D - [Axis 0]
2D - [Axis 0 (Row), Axis 1 (Column)]
'''


X = [[1,2,3], [4,5,6], [7,8,9]]
arr=np.array(X)
print(arr, arr.shape)
print(f"Summation of rows = {arr.sum(axis=0)}") # column is constant, addition occurs between different row elements
print(f"Summation of columns = {arr.sum(axis=1)}") # row is constant, addition occurs between different column elements
print(f"Transpose of a matrix = \n{arr.T}")
print(f"Sum of all the elements of a single row = {arr[2].sum()}")
print(f"Sum of all the elements of a single column = {arr[:,2].sum()}")
print(f"Trace of the matrix (summation of the primary diagonal elements) = {np.trace(X)}")
print(f"Determinant of the matrix = {np.linalg.det(X)}")

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
Summation of rows = [12 15 18]
Summation of columns = [ 6 15 24]
Transpose of a matrix =
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum of all the elements of a single row = 24
Sum of all the elements of a single column = 18
Trace of the matrix (summation of the primary diagonal elements) = 15
Determinant of the matrix = 0.0

In [14]:
arr_flat = arr.flatten()
print("The flattened version of the matrix  =", arr_flat)
print(arr.ravel())

The flattened version of the matrix  = [1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]

In [15]:
one = np.array([1,64,4,634, 2])
print(f"Index that contains the maximum-valued element = {one.argmax()}")
print(f"Index that contains the minimum-valued element = {one.argmin()}")
print(f"Sorted array = {np.sort(one)}")
print(f"{np.argsort(one)}")

Index that contains the maximum-valued element = 3
Index that contains the minimum-valued element = 0
Sorted array = [  1   2   4  64 634]
[0 4 2 1 3]

In [16]:
arr = np.array([[1,2,3], [4,5,6], [7,1,0]])
print(arr)
print("*"*80)
print(arr.argmin()) # return the index where the lowest element is located
print(arr.argmax()) # return the index where the highest element is located
print("*"*80)
print(arr.argmax(axis=0))
print(arr.argmax(axis=1))
print("*"*80)
print(arr.argmin(axis=0))
print(arr.argmin(axis=1))

[[1 2 3]
 [4 5 6]
 [7 1 0]]
********************************************************************************
8
6
********************************************************************************
[2 1 1]
[2 2 0]
********************************************************************************
[0 2 2]
[0 0 2]

In [17]:
print("*"*40+"Arr1"+"*"*40)
ar1 = arr.copy()
print(ar1)
print("*"*40+"Arr2"+"*"*40)
ar2 = np.array([[1,2,1], [4,0,6], [8,1,0]])
print(ar2)
print("*"*40+"Matrix Addition"+"*"*40)
print(ar1+ar2)
print("*"*40+"Matrix dot product"+"*"*40)
print(ar1*ar2)
print("*"*40+"Matrix Multiplication"+"*"*40)
print(np.matmul(ar1,ar2))
print("*"*40+"MAtrix Inverse"+"*"*40)
print(np.linalg.inv(ar2))

****************************************Arr1****************************************
[[1 2 3]
 [4 5 6]
 [7 1 0]]
****************************************Arr2****************************************
[[1 2 1]
 [4 0 6]
 [8 1 0]]
****************************************Matrix Addition****************************************
[[ 2  4  4]
 [ 8  5 12]
 [15  2  0]]
****************************************Matrix dot product****************************************
[[ 1  4  3]
 [16  0 36]
 [56  1  0]]
****************************************Matrix Multiplication****************************************
[[33  5 13]
 [72 14 34]
 [11 14 13]]
****************************************MAtrix Inverse****************************************
[[-0.06382979  0.0106383   0.12765957]
 [ 0.5106383  -0.08510638 -0.0212766 ]
 [ 0.04255319  0.15957447 -0.08510638]]

In [18]:
# Pandas :
import pandas as pd

In [19]:
myDictionary = {
    "name": ["steve", 'tony', 'peter', 'natasha', 'wanda'],
    "marks": [80, 96, 95, 87, 80],
    "city": ["queens", "new_york", "brooklyn", "volgograd", "sokovia"]

}
print(myDictionary)
df = pd.DataFrame(myDictionary)
print(df)
df.to_csv('avengers.csv')

{'name': ['steve', 'tony', 'peter', 'natasha', 'wanda'], 'marks': [80, 96, 95, 87, 80], 'city': ['queens', 'new_york', 'brooklyn', 'volgograd', 'sokovia']}
      name  marks       city
0    steve     80     queens
1     tony     96   new_york
2    peter     95   brooklyn
3  natasha     87  volgograd
4    wanda     80    sokovia

In [20]:
mycsv = pd.read_csv('avengers.csv')
print("*"*90)
print(mycsv, type(mycsv))
print("*"*90)
print(mycsv['name'])

******************************************************************************************
   Unnamed: 0     name  marks       city
0           0    steve     80     queens
1           1     tony     96   new_york
2           2    peter     95   brooklyn
3           3  natasha     87  volgograd
4           4    wanda     80    sokovia <class 'pandas.core.frame.DataFrame'>
******************************************************************************************
0      steve
1       tony
2      peter
3    natasha
4      wanda
Name: name, dtype: object

In [21]:
mycsv['marks'][2] = 99
print(mycsv)

   Unnamed: 0     name  marks       city
0           0    steve     80     queens
1           1     tony     96   new_york
2           2    peter     99   brooklyn
3           3  natasha     87  volgograd
4           4    wanda     80    sokovia

/tmp/ipykernel_34086/1910506485.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  mycsv['marks'][2] = 99
/tmp/ipykernel_34086/1910506485.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mycsv['marks'][2] = 99

In [22]:
df.head(3) # view first few rows of a dataframe by default it show for the first 5

    name  marks      city
0  steve     80    queens
1   tony     96  new_york
2  peter     95  brooklyn

In [23]:
df.tail(3) # view last few rows of a dataframe by default it show for the last 5

      name  marks       city
2    peter     95   brooklyn
3  natasha     87  volgograd
4    wanda     80    sokovia

In [24]:
new_df = pd.DataFrame(np.random.rand(334,5), index = np.arange(334))
print(new_df)

            0         1         2         3         4
0    0.565871  0.072037  0.331380  0.348658  0.233459
1    0.688182  0.586374  0.335176  0.112725  0.388190
2    0.271769  0.037551  0.424272  0.799062  0.190484
3    0.177546  0.750148  0.203852  0.783497  0.470838
4    0.751185  0.309489  0.086412  0.941537  0.051171
..        ...       ...       ...       ...       ...
329  0.542077  0.225047  0.157834  0.022127  0.745757
330  0.366934  0.756213  0.751136  0.476631  0.401673
331  0.057575  0.573009  0.954018  0.430559  0.381172
332  0.908341  0.055465  0.978386  0.456115  0.785134
333  0.976718  0.669172  0.828750  0.284790  0.038081

[334 rows x 5 columns]

In [25]:
new_df.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.497739    0.506928    0.495194    0.493548    0.495437
std      0.301780    0.295291    0.297615    0.285596    0.281398
min      0.000572    0.003316    0.002151    0.001110    0.009407
25%      0.231976    0.231076    0.228486    0.252971    0.260521
50%      0.498659    0.514990    0.481700    0.478450    0.484782
75%      0.764127    0.754411    0.775573    0.750283    0.742757
max      0.992581    0.997129    0.998756    0.997784    0.995169

In [26]:
new_df_np=new_df.to_numpy()

In [27]:
print(type(new_df_np))

<class 'numpy.ndarray'>

In [28]:
new_df.sort_index(axis =0, ascending = False)

            0         1         2         3         4
333  0.976718  0.669172  0.828750  0.284790  0.038081
332  0.908341  0.055465  0.978386  0.456115  0.785134
331  0.057575  0.573009  0.954018  0.430559  0.381172
330  0.366934  0.756213  0.751136  0.476631  0.401673
329  0.542077  0.225047  0.157834  0.022127  0.745757
..        ...       ...       ...       ...       ...
4    0.751185  0.309489  0.086412  0.941537  0.051171
3    0.177546  0.750148  0.203852  0.783497  0.470838
2    0.271769  0.037551  0.424272  0.799062  0.190484
1    0.688182  0.586374  0.335176  0.112725  0.388190
0    0.565871  0.072037  0.331380  0.348658  0.233459

[334 rows x 5 columns]

In [29]:
new_df.head()

          0         1         2         3         4
0  0.565871  0.072037  0.331380  0.348658  0.233459
1  0.688182  0.586374  0.335176  0.112725  0.388190
2  0.271769  0.037551  0.424272  0.799062  0.190484
3  0.177546  0.750148  0.203852  0.783497  0.470838
4  0.751185  0.309489  0.086412  0.941537  0.051171

In [30]:
new_df2 = new_df.copy()
new_df2[3][1] = 7865 # change the value of row 1, column 3
print(new_df2)

            0         1         2            3         4
0    0.565871  0.072037  0.331380     0.348658  0.233459
1    0.688182  0.586374  0.335176  7865.000000  0.388190
2    0.271769  0.037551  0.424272     0.799062  0.190484
3    0.177546  0.750148  0.203852     0.783497  0.470838
4    0.751185  0.309489  0.086412     0.941537  0.051171
..        ...       ...       ...          ...       ...
329  0.542077  0.225047  0.157834     0.022127  0.745757
330  0.366934  0.756213  0.751136     0.476631  0.401673
331  0.057575  0.573009  0.954018     0.430559  0.381172
332  0.908341  0.055465  0.978386     0.456115  0.785134
333  0.976718  0.669172  0.828750     0.284790  0.038081

[334 rows x 5 columns]

/tmp/ipykernel_34086/2608711368.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  new_df2[3][1] = 7865 # change the value of row 1, column 3

In [31]:
print(new_df.loc[1:3]) #view the df from row =1 to row =3

          0         1         2         3         4
1  0.688182  0.586374  0.335176  0.112725  0.388190
2  0.271769  0.037551  0.424272  0.799062  0.190484
3  0.177546  0.750148  0.203852  0.783497  0.470838

In [32]:
new_df.loc[0,4] = 664 # locate the element at 0th row and 4th column and change its value
new_df.head()

          0         1         2         3           4
0  0.565871  0.072037  0.331380  0.348658  664.000000
1  0.688182  0.586374  0.335176  0.112725    0.388190
2  0.271769  0.037551  0.424272  0.799062    0.190484
3  0.177546  0.750148  0.203852  0.783497    0.470838
4  0.751185  0.309489  0.086412  0.941537    0.051171

In [33]:
new_df.columns = list("ABCDE")
new_df.loc[0, 'D'] = 5 # using loc we access an element using row index and column name
new_df.iloc[0, 1] = 5  # using iloc we access an element using row index and column index
new_df.head()

          A         B         C         D           E
0  0.565871  5.000000  0.331380  5.000000  664.000000
1  0.688182  0.586374  0.335176  0.112725    0.388190
2  0.271769  0.037551  0.424272  0.799062    0.190484
3  0.177546  0.750148  0.203852  0.783497    0.470838
4  0.751185  0.309489  0.086412  0.941537    0.051171

In [34]:
new_df.drop('B', axis=1, inplace = True)
new_df.head()

          A         C         D           E
0  0.565871  0.331380  5.000000  664.000000
1  0.688182  0.335176  0.112725    0.388190
2  0.271769  0.424272  0.799062    0.190484
3  0.177546  0.203852  0.783497    0.470838
4  0.751185  0.086412  0.941537    0.051171

In [37]:
new_df.loc[(new_df['A']<0.3)&(new_df['C']>0.1)]

            A         C         D         E
2    0.271769  0.424272  0.799062  0.190484
3    0.177546  0.203852  0.783497  0.470838
5    0.062985  0.602786  0.646278  0.516496
8    0.046966  0.964393  0.005807  0.262561
12   0.122258  0.399217  0.826801  0.773004
..        ...       ...       ...       ...
307  0.155443  0.229359  0.704295  0.620040
313  0.041813  0.492840  0.100535  0.429108
324  0.255033  0.220628  0.928748  0.657238
326  0.020341  0.998756  0.654961  0.986402
331  0.057575  0.954018  0.430559  0.381172

[96 rows x 4 columns]

In [38]:
#delete a row
new_df.drop(0, axis=0, inplace = True)
new_df.head()

          A         C         D         E
1  0.688182  0.335176  0.112725  0.388190
2  0.271769  0.424272  0.799062  0.190484
3  0.177546  0.203852  0.783497  0.470838
4  0.751185  0.086412  0.941537  0.051171
5  0.062985  0.602786  0.646278  0.516496

In [39]:
new_df.reset_index(drop=True, inplace=True)
new_df.head()

          A         C         D         E
0  0.688182  0.335176  0.112725  0.388190
1  0.271769  0.424272  0.799062  0.190484
2  0.177546  0.203852  0.783497  0.470838
3  0.751185  0.086412  0.941537  0.051171
4  0.062985  0.602786  0.646278  0.516496