In [ ]:
print("Hello World!")
print("Welcome to the Python Basics class of Autumn Intership 2026 !! ")

Hello World!
Welcome to the Python Basics class of Autumn Intership 2026 !!

In [ ]:
# What if I need to note something in my program and I don't want that line to be executed? This is a single line comment
a,b = 10, 20
print(a+b)
'''
This is an example of multiline comments!
print(a+b)
'''

30

'\nThis is an example of multiline comments!\nprint(a+b)\n'

In [ ]:
# variable : A named memory location. To store some value.. Can the value be changed later on ? YES!
a=12
print(a)
a=21
print(a)

# integer variables : will contain integer values
myInteger = 16754
print(myInteger, type(myInteger)) # type(): function that returns the datatype of the variable used

# float variables : will contain decimal values
pi = 3.14
print(pi, type(pi))

# string variables : will contain sentences or words etc..
name = "Harry Potter"
print(name, type(name))

# boolean variables : True or False
isThisClassInteresting = True
print(isThisClassInteresting, type(isThisClassInteresting))

12
21
16754 <class 'int'>
3.14 <class 'float'>
Harry Potter <class 'str'>
True <class 'bool'>

In [ ]:
# Type Casting: Conversion of one datatype to another

#implicit typecasting
print(myInteger, type(myInteger))
myInteger = myInteger + pi
print(myInteger, type(myInteger))

#explicit typecasting / coercion
myInteger = int(myInteger)
print(myInteger, type(myInteger))

myInteger = str(myInteger)
print(myInteger, type(myInteger))

myInteger = bool(myInteger)
print(myInteger, type(myInteger))

print(int(isThisClassInteresting))

True <class 'bool'>
4.140000000000001 <class 'float'>
4 <class 'int'>
4 <class 'str'>
True <class 'bool'>
1

In [ ]:
# Basic Operations:
numerator = 11
denominator = 2
print("numerator + denominator = {numerator+denominator}") # f -> formatted strings
print(f"numerator + denominator = {numerator+denominator}") # Addition
print(f"numerator - denominator = {numerator-denominator}") # Subtraction
print(f"numerator * denominator = {numerator*denominator}") # Multiplication
print(f"numerator / denominator = {numerator/denominator}") # float division
print(f"numerator // denominator = {numerator//denominator}") # integer division
print(int(2.9999))
print(f"numerator % denominator = {numerator%denominator}")
print(f"numerator ** denominator = {numerator**denominator}")

demon = 0
try:
  print(numerator/demon)
except Exception as emotionalDamage:
  print(emotionalDamage)

print("My name is Voldemort")

numerator + denominator = {numerator+denominator}
numerator + denominator = 13
numerator - denominator = 9
numerator * denominator = 22
numerator / denominator = 5.5
numerator // denominator = 5
2
numerator % denominator = 1
numerator ** denominator = 121
division by zero
My name is Voldemort

In [ ]:
# String Operations
lastName = "Dommaraju"
firstName = "Gukesh"

'''
-6 -5  -4  -3  -2  -1
G   u   k   e   s   h
0   1   2   3   4   5
'''
print(lastName[4])
name = firstName + " " + lastName # string concatenation
print(f"the concatenated string = {name}")
print(f"length of the concatenated string = {len(name)}")

# Substrings: A subsequence in a string stringName[lowerBound:Upperbound]
print(f"substring example 1: {name[2:5]}")
print(f"substring example 2: {name[:5]}")
print(f"substring example 3: {name[6:]}")
print(f"substring example 4: {name[-5:-2]}")

"""
Home-work:
print(f"substring example 4: {name[1:-5]}")
print(f"substring example 4: {name[::-1]}")

"""

a
the concatenated string = Gukesh Dommaraju
length of the concatenated string = 16
substring example 1: kes
substring example 2: Gukes
substring example 3:  Dommaraju
substring example 4: ara

'\nHome-work:\nprint(f"substring example 4: {name[1:-5]}")\nprint(f"substring example 4: {name[::-1]}")\n\n'

In [ ]:
# Conditional Statements:

'''
if condition1:
  statement1
elif condition2: (elif means else if)
  statement2
else:
  statement3
'''


physics = 60
maths = 60

if(physics >= 85 and maths >=85): # and here is a logical operator and the result is TRUE if both the conditions are TRUE
  print("Pen + Diary")
elif(physics >= 85 or maths >=85 ): # or here is a logical operator and the result is TRUE if either condition or both the conditions are TRUE
  print("Pen")
else:
  print("FLYING CHAPPAL RECEIVED")

FLYING CHAPPAL RECEIVED

In [ ]:
# FOR Loop : looping means doing the same task again and again

for i in range(5):
  print(i)

  # i : loop control variable
  # range() range(n): 0 ,1,2,3, .... , n-1

# DRY RUN

'''
1st iteration:
i = 0
print(0)
By default the value of i is incremented by 1 in each iteration
i = i+1 = 0+1 = 1

2nd iteration:
i = 1
print(1)
i = i+1 = 1+1 = 2

3rd iteration:
i = 2
print(2)
i = i+1 = 2+1 = 3

4th iteration:
i = 3
print(3)
i = i+1 = 3+1 = 4


5th iteration:
i = 4
print(4)
i = i+1 = 4+1 = 5

6th iteration:
i=5
this fails the loop condition. Hence, terminate the loop
'''

0
1
2
3
4

'\n1st iteration:\ni = 0\nprint(0)\nBy default the value of i is incremented by 1 in each iteration\ni = i+1 = 0+1 = 1\n\n2nd iteration:\ni = 1\nprint(1)\ni = i+1 = 1+1 = 2\n\n3rd iteration:\ni = 2\nprint(2)\ni = i+1 = 2+1 = 3\n\n4th iteration:\ni = 3\nprint(3)\ni = i+1 = 3+1 = 4\n\n\n5th iteration:\ni = 4\nprint(4)\ni = i+1 = 4+1 = 5 \n\n6th iteration:\ni=5\nthis fails the loop condition. Hence, terminate the loop\n'

In [ ]:
# program 1: write a python program to swap two numbers:
a = 20
b = 30
temp = a
a = b
b = temp
print(a,b)

# program 1: write a python program to swap two numbers:
a = 20
b = 30
a = a + b
b = a - b
a = a - b
print(a,b)

30 20
30 20

In [ ]:
# Write a python program to print the following pattern:
'''
1
22
333
4444
55555
'''
for i in range(1,6):
  for j in range(i):
    print(i, end = " ")
  print()

print()

# New Approach
for i in range(1,6):
  # for j in range(i):
  #   print(i, end = " ")
  print(str(i)*i)

print()
print(str(1)*4)

1
2 2
3 3 3
4 4 4 4
5 5 5 5 5

1
22
333
4444
55555

1111

In [ ]:
# Some more dataypes: Lists
# Lists are mutable
myList = ["Harry", 9, 31.78]
print(myList, type(myList))
myList = ["Harry", "Hermione", "Ron", "Draco", "Snape"] # length of the list = 5
print(myList)
"""
Indexing in a list is the exactly same as that of a string
"""
#list slicing:
print(myList[1:3])
print(myList[:3])
print(myList[2:])
print(myList[::-2])
print(myList[::1])
# myList[lowerBound:upperBound:step]
print("*"*30)

print("FOR LOOP EXAMPLE FOR LISTS : Method 1")
for i in range(len(myList)): # len() calculates the length of a list
  print(i)
  print(myList[i])

print("*"*30)
print("FOR LOOP EXAMPLE FOR LISTS : Method 2")
for i in myList: # len() calculates the length of a list
  print(i)
print("*"*30)
print("FOR LOOP EXAMPLE FOR LISTS : Step value")
for i in range(1,len(myList),2):
  print(myList[i], end = ' ')

['Harry', 9, 31.78] <class 'list'>
['Harry', 'Hermione', 'Ron', 'Draco', 'Snape']
['Hermione', 'Ron']
['Harry', 'Hermione', 'Ron']
['Ron', 'Draco', 'Snape']
['Snape', 'Ron', 'Harry']
['Harry', 'Hermione', 'Ron', 'Draco', 'Snape']
******************************
FOR LOOP EXAMPLE FOR LISTS : Method 1
0
Harry
1
Hermione
2
Ron
3
Draco
4
Snape
******************************
FOR LOOP EXAMPLE FOR LISTS : Method 2
Harry
Hermione
Ron
Draco
Snape
******************************
FOR LOOP EXAMPLE FOR LISTS : Step value
Hermione Draco

In [ ]:
myList = ["Harry", "Hermione", "Ron", "Draco", "Snape"] # length of the list = 5
print("*"*30)
print("FOR LOOP EXAMPLE FOR LISTS WITH IF_ELSE")
for i in myList:
  if (i == "Draco"):
    print("My Father will hear about this")
  elif (i ==  "Snape"):
    print("50 points from Gryffindor")
  else:
    print("Gryffindor Rocks!!")

******************************
FOR LOOP EXAMPLE FOR LISTS WITH IF_ELSE
Gryffindor Rocks!!
Gryffindor Rocks!!
Gryffindor Rocks!!
My Father will hear about this
50 points from Gryffindor

In [ ]:
# More string operations:
from itertools import count
#stripping whitespaces
text_with_spaces = "      Prof Severus Snape  "
print(text_with_spaces, len(text_with_spaces))
stripped_text_with_spaces = text_with_spaces.strip() # strip() removes the extra whitespaces from both ends of a string
print(stripped_text_with_spaces, len(stripped_text_with_spaces))
print("*"*70)
#strip specific characters
text_with_chars = "### Prof Severus ## Snape"
print(text_with_chars, len(text_with_chars))
stripped_text_with_chars = text_with_chars.strip('#') # strip('#') removes the extra '#' from both ends of a string. any occurence of # within the string will not be removeed
print(stripped_text_with_chars, len(stripped_text_with_chars))
print("*"*70)
#replacesubstrings:
text_with_no_spaces = text_with_spaces.replace(" ","")
print(text_with_no_spaces, len(text_with_no_spaces))
print("*"*70)
original_text = "Potter, you stupid fellow, you might be in some serious trouble."
print(original_text)
new_text = original_text.replace("serious", "sirius")
print(new_text)
print("*"*70)
# Find a substring/ locate the position of a substring
findPosition = original_text.find("serious")
print(findPosition)
print("*"*70)
count = original_text.count("you")
print(count)

      Prof Severus Snape   26
Prof Severus Snape 18
**********************************************************************
### Prof Severus ## Snape 25
 Prof Severus ## Snape 22
**********************************************************************
ProfSeverusSnape 16
**********************************************************************
Potter, you stupid fellow, you might be in some serious trouble.
Potter, you stupid fellow, you might be in some sirius trouble.
**********************************************************************
48
**********************************************************************
2

In [ ]:
# functions: is a code segment that we wish to reuse again and again

def add(x,y):
  # def means to define a function
  # we are defining a function add() that takes input two parameters x and y
  result = x+y
  print("Hurray!! I got the result!!! before the return statement")
  return x+y # the return keyword is used inside a function to send the result(s) back to the caller. the return statement marks the end of a function.
  print("Hurray!! I got the result!!!")


add_result = add(30,40)
print(add_result)

Hurray!! I got the result!!! before the return statement
70

In [ ]:
# WAPP to print all the prime numbers within a range [lb,ub] using functions

lb = int(input("Enter the lower bound = "))
ub = int(input("Enter the upper bound = "))

def isPrime(n):
  for i in range(2,n):
    if n%i==0:
      return False
  return True

for i in range(lb, ub+1):
  if isPrime(i):
    print(f"{i} is a PRIME NUMBER")

Enter the lower bound = 20
Enter the upper bound = 30
23 is a PRIME NUMBER
29 is a PRIME NUMBER

In [ ]:
# WHILE LOOP
i = 0 # loop counter variable
while(i<5):
  print(i, end = ' ')
  i += 1 # i = i+1

"""
DRY RUN

iter 1:
i=0
does it satisfy the condition i<5 ? it does:
print(0)
i=0+1 = 1

iter 2:
i=1
does it satisfy the condition i<5 ? it does:
print(1)
i=1+1 = 2

iter 3:
i=2
does it satisfy the condition i<5 ? it does:
print(2)
i=2+1 = 3

iter 4:
i=3
does it satisfy the condition i<5 ? it does:
print(3)
i=3+1 = 4

iter 5:
i=4
does it satisfy the condition i<5 ? it does:
print(5)
i=4+1 = 5

iter 6:
i=5
does it satisfy the condition i<5 ? NO:
Terminate the looop
"""

0 1 2 3 4

'\nDRY RUN\n\niter 1:\ni=0 \ndoes it satisfy the condition i<5 ? it does:\nprint(0)\ni=0+1 = 1\n\niter 2:\ni=1 \ndoes it satisfy the condition i<5 ? it does:\nprint(1)\ni=1+1 = 2\n\niter 3:\ni=2 \ndoes it satisfy the condition i<5 ? it does:\nprint(2)\ni=2+1 = 3\n\niter 4:\ni=3 \ndoes it satisfy the condition i<5 ? it does:\nprint(3)\ni=3+1 = 4\n\niter 5:\ni=4 \ndoes it satisfy the condition i<5 ? it does:\nprint(5)\ni=4+1 = 5\n\niter 6:\ni=5 \ndoes it satisfy the condition i<5 ? NO:\nTerminate the looop \n'

In [ ]:
# WAPP to checkk if a number is an Armstrong Number
# 153 = 1^3 + 5^3 + 3^3

def isArmstrong(n):
  l = len(str(n))
  temp = n
  sum = 0
  while(temp>0):
    rem = temp%10
    sum = sum + pow(rem,l)
    temp=temp//10
  if sum == n:
    print(f"{n} is an ARMSTRONG NUMBER")
  else:
    print(f"{n} is not an ARMSTRONG NUMBER")

isArmstrong(int(input("Enter a number to check if it is an Armstrong Number = ")))

Enter a number to check if it is an Armstrong Number = 8208
8208 is an ARMSTRONG NUMBER

In [ ]:
# RECURSION : A function calls itself

# Write a program to calculate thr factorial of a number using recursion
# 5! = 5*4*3*2*1 = 5 * 4!
# 4! = 4*3*2*1 = 4*3!
# 3! = 3*2*1
# n! = n*(n-1)!

def factorial(x):
  # base case:
  if(x==0 or x==1):
    return 1
  # recursive case:
  else:
    return x * factorial(x-1)

n = int(input("Enter a number = "))
print(f"The factorial of {n} is {factorial(n)}")

'''
factorial(5)
  is (5==0 or 5==1) ? NO
  return 5 * factorial(4) = 5 * 24

factorial(4)
  is (4==0 or 4==1) ? NO
  return 4 * factorial(3) = 4 * 6  = 24

factorial(3)
  is (3==0 or 3==1) ? NO
  return 3 * factorial(2) = 3 * 2 = 6

factorial(2)
  is (2==0 or 2==1) ? NO
  return 2 * factorial(1) = 2 * 1 = 2

factorial(1)
  is (1==0 or 1==1) ? TRUE
  return 1
'''

fact = 1
for i in range(1,n+1):
  fact = fact * i
print(fact)

Enter a number = 5
The factorial of 5 is 120
120

In [ ]:
# WAPP pow() using recursion

def power(base, exp):
    if exp == 0:
        return 1
    return base * power(base, exp - 1)

power(2,3)

'''
power(base= 2,exp= 3)
  is (3=0) ? NO
  return 2 * power(2,2) = 2*4 = 8

power(base= 2,exp= 2)
  is (2=0) ? NO
  return 2 * power(2,1) = 2*2 =4

power(base= 2,exp= 1)
  is (1=0) ? NO
  return 2 * power(2,0) = 2* 1 = 2

 power(base= 2,exp= 0)
  is (0=0) ? YES
  return 1

'''
 # 2^3 = 2*pow(2,2)

8

In [10]:
# Lists revisited:

# append : add at the end of a list
myList = [1,2,3,4,5,6,7,8,9,7]
print(f"original list = {myList}")
myList.append(25)
print(f"modified list = {myList}")
# remove an element from the list
myList.remove(7) # remove(n) : removes the first occurence of n from the list
print(f"modified list after removing an element from the list =  {myList}")
#pop
myList.pop(7)
print(f"modified list after popping an element from the list =  {myList}")
#by default pop() removes the last element if no index is specified
myList.pop()
print(f"modified list after popping an element from the list =  {myList}")
#insert an element at some specific index
myList.insert(1,100)
print(f"modified list after inserting an element into the list =  {myList}")

# Lists are mutable: we can update a value at some given index
myList[3] = 10
myList[5] = 20
print(f"modified list after updating an element of the list =  {myList}")
print("*"*90)
fruits = ['apple', 'banana', 'cherry', 'orange', 'mango']
# create a fruit basket that will only carry fruits having an 'o' in it's name.
fruitBasket = []
for i in fruits:
  if 'o' in i:
    fruitBasket.append(i)
print(f"My fruit basket = {fruitBasket}")

# list comprehension:
fruitBasket_lc = [i for i in fruits if 'o' in i]
print(f"My fruit basket using list comprehension = {fruitBasket}")
print("*"*90)
# list input using list comprehension
# approach 1:
'''
# myListInput = [int(x) for x in input().split()]
# print(myListInput)
'''
#approach 2:
'''
lst = [int(input("Enter a no.")) for _ in range (5)]
print(lst)'''

original list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 7]
modified list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 7, 25]
modified list after removing an element from the list =  [1, 2, 3, 4, 5, 6, 8, 9, 7, 25]
modified list after popping an element from the list =  [1, 2, 3, 4, 5, 6, 8, 7, 25]
modified list after popping an element from the list =  [1, 2, 3, 4, 5, 6, 8, 7]
modified list after inserting an element into the list =  [1, 100, 2, 3, 4, 5, 6, 8, 7]
modified list after updating an element of the list =  [1, 100, 2, 10, 4, 20, 6, 8, 7]
******************************************************************************************
My fruit basket = ['orange', 'mango']
My fruit basket using list comprehension = ['orange', 'mango']
******************************************************************************************

'\nlst = [int(input("Enter a no.")) for _ in range (5)]\nprint(lst)'

In [11]:
# Dictionaries: key-value pair
hogwarts = {"Gryffindor":'Hermione', "Ravenclaw":'Luna', "Slytherin": "Draco", 'Hufflepuff':'Cedric', 'Gryffindor':'Harry'}
print(hogwarts)
# print(hogwarts[0]) : An element of a Dictionary can be accessed only with the key value and not any index value
print(hogwarts['Slytherin'])
print(hogwarts.keys()) # keys(): collects all the keys associated in the dictionary
print(hogwarts.values()) # values(): collects all the values associated in the dictionary
print(hogwarts.items()) # items(): collects all the key-value pairs associated in the dictionary
# Dictonaries are mutable
hogwarts['Gryffindor'] = "Ron"
print(hogwarts)

for key, value in hogwarts.items():
  print(f"key = {key} and value = {value}" )

{'Gryffindor': 'Harry', 'Ravenclaw': 'Luna', 'Slytherin': 'Draco', 'Hufflepuff': 'Cedric'}
Draco
dict_keys(['Gryffindor', 'Ravenclaw', 'Slytherin', 'Hufflepuff'])
dict_values(['Harry', 'Luna', 'Draco', 'Cedric'])
dict_items([('Gryffindor', 'Harry'), ('Ravenclaw', 'Luna'), ('Slytherin', 'Draco'), ('Hufflepuff', 'Cedric')])
{'Gryffindor': 'Ron', 'Ravenclaw': 'Luna', 'Slytherin': 'Draco', 'Hufflepuff': 'Cedric'}
key = Gryffindor and value = Ron
key = Ravenclaw and value = Luna
key = Slytherin and value = Draco
key = Hufflepuff and value = Cedric

In [12]:
# Tuples
myTuple = (1,2,3,4,4)
print(myTuple,type(myTuple))
print(myTuple[1])
#tuples are immutable, which means no value in a tuple can be updated
#myTuple[1] = 45

myTuple = list(myTuple)
print(myTuple, type(myTuple))
myTuple[2]=45
myTuple = tuple(myTuple)
print(myTuple, type(myTuple))

(1, 2, 3, 4, 4) <class 'tuple'>
2
[1, 2, 3, 4, 4] <class 'list'>
(1, 2, 45, 4, 4) <class 'tuple'>

In [14]:
# lists = [], tuple = (), dictionaries = {key:value}, Sets = {}
# Sets
mySet = {1,2,3,4,5,6,10,7,8,9}
print(mySet, type(mySet))
mySet.add(8)
print(mySet)
mySet.remove(8)
print(mySet)
myList.append(100)
print(f"myList = {myList}")
mySet_list = set(myList)
print(f"after typecasting myList into a set = {mySet_list} ")

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10} <class 'set'>
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{1, 2, 3, 4, 5, 6, 7, 9, 10}
myList = [1, 100, 2, 10, 4, 20, 6, 8, 7, 100]
after typecasting myList into a set = {1, 2, 100, 4, 6, 7, 8, 10, 20}

In [24]:
import math as m
print(m.sqrt(625))
print(round(0.49))
print(round(0.50000001))
print(round(0.51))

25.0
0
1
1

In [29]:
#Class and Objects
# CLASS:  It is a blueprint for creating an object
# OBJECT: Is an instance of the class
class Student:
  compulsory_subject = "Mathematics"

# creating an object (an instance of the class)
s1 = Student()
print(s1.compulsory_subject)
print(f"The address of s1 = {s1}")
s2 = Student()
print(s2.compulsory_subject)
print(f"The address of s2 = {s2}")

Mathematics
The address of s1 = <__main__.Student object at 0x79d854a19010>
Mathematics
The address of s2 = <__main__.Student object at 0x79d83dfea0d0>

In [39]:
# this is an example of default constructor
class Car:
  def printCarFeatures(self):
    color = 'blue'
    brand = 'mercedes'
    print(color, brand)

car1 = Car()
car1.printCarFeatures()
# print(car1.color)
# print(car1.brand)

car2 = Car()
car2.printCarFeatures()
# print(car2.color)
# print(car2.brand)

blue mercedes
blue mercedes

In [36]:
# __init__(): Constructor of a class
# All Classes have an __init__(), which is always executed when the class is initiated .. i.e. when an object is created

class Student:
  def __init__(self, fullName):
    self.name = fullName
  def printName(self):
    print(f"self value = {self}")
    return self.name
s1 = Student("Miguel Diaz")
s2 = Student("Robby Lawrence")

print(f"{"*"*20} DEALING WITH object s1 {"*"*20}")
print(f"object value = {s1}")
name1 = s1.printName()
print(name1)
print(f"{"*"*20} DEALING WITH object s2 {"*"*20}")
print(f"object value = {s1}")
name2 = s2.printName()
print(name2)
# self: the self keyword is a reference to the current object
# self is also used to access variables that belong to a class

******************** DEALING WITH object s1 ********************
object value = <__main__.Student object at 0x79d854a19550>
self value = <__main__.Student object at 0x79d854a19550>
Miguel Diaz
******************** DEALING WITH object s2 ********************
object value = <__main__.Student object at 0x79d854a19550>
self value = <__main__.Student object at 0x79d83d8f7ed0>
Robby Lawrence

In [41]:
# constructors are of 3 types : 1. default constructor 2. non-parameterized 3. paramterized constructor


# example of non-parameterised constructor
class Student:
  def __init__(self):
    self.sub1 = 'Physics'
    self.sub2 = 'Mathematics'
  def printName(self, fullName):
    print(f"The student {fullName} has taken the courses {self.sub1} and {self.sub2}")

s1 = Student()
s1.printName("Miguel")

s2= Student()
s2.printName("Robby")

The student Miguel has taken the courses Physics and Mathematics
The student Robby has taken the courses Physics and Mathematics

In [53]:
# example of non-parameterised constructor
'''
Class and Instance variables:

Class variable:
A variable which has a fixed value even if the objects change

Instance variables:
The values of the variables sub1, sub2, fullName, totalMarks may change with different objects. ie different objects may have different values for these variables.
thus, they are instance variables.
'''

'''
Method : is  a function that is defined in a class
'''

class Student:
  institute = "IDEAS-TIH"
  def __init__(self, sub1, sub2, name):
    self.sub1 = sub1
    self.sub2 = sub2
    self.fullName = name

  @staticmethod
  def printMyWish(myName):
    print(f"I {myName}, wish this class ends soon !!!!!!!!!!")

  def printMyWishSecond(self):
    print(f"I am {self.fullName} and I wish to have a cup of tea after this class is over !")

  def printMarks(self, totalMarks):
    print(f"The student {self.fullName} of {Student.institute} has taken the courses {self.sub1} and {self.sub2} and scored a total of = {totalMarks}")
    self.printMyWishSecond()
    Student.printMyWish(self.fullName)


s1 = Student('Mathematics', 'Physics', "Miguel")
s1.printMarks(85)

# s2= Student('Mathematics', 'Computer Science', "Robby")
# s2.printMarks(86)

The student Miguel of IDEAS-TIH has taken the courses Mathematics and Physics and scored a total of = 85
I am Miguel and I wish to have a cup of tea after this class is over !
I Miguel, wish this class ends soon !!!!!!!!!!

In [ ]:
# Book Suggestion: Python basics a Self-Teaching Introduction by H Basin

In [1]:
# Abstraction:   Hiding the implementational details of a class and showing only the essential features to the user
# Encapsulation: Wrapping data and functions into a single unit(object). Basically it is data + method

class Car:
  def __init__(self, number):
    self.acc = False
    self.clutch = False
    self.brake = False
    self.carNumber = number
  def startCar(self):
    self.clutch = True
    self.acc = True
    print(f"In car {self.carNumber}, clutch turned {self.clutch} and accelerator turned {self.acc} so start the car")
  def stopCar(self):
    self.brake = True
    self.acc = False
    print(f"In car {self.carNumber}, Brake turned {self.brake} and accelerator turned {self.acc} so stop the car")

car1 = Car(1)
car2 = Car(2)

car1.startCar()
car2.startCar()

car1.stopCar()
car2.stopCar()

In car 1, clutch turned True and accelerator turned True so start the car
In car 2, clutch turned True and accelerator turned True so start the car
In car 1, Brake turned True and accelerator turned False so stop the car
In car 2, Brake turned True and accelerator turned False so stop the car

In [2]:
# Inheritance:

class Employee: # Parent class
  def __init__(self, name, id):
    self.name = name
    self.id = id

  def showEmployeeDetails(self):
    print(f"The name of employee {self.id} is {self.name} ")

class Programmer(Employee): # child class
  def showLanguage(self, lang):
    print(f"The Programmer {self.name} works using {lang}")

# e1 = Employee("Archit", 101)
# e1.showEmployeeDetails()

p1 = Programmer("Bipasha", 102)
p1.showEmployeeDetails()
p1.showLanguage("Java")

The name of employee 102 is Bipasha
The Programmer Bipasha works using Java

In [3]:
class A:
  def feature1(self):
    print("This is feature 1 of class A")
  def feature2(self):
    print("This is feature 2 of class A")

class B(A): # single-level inheritance
  def feature3(self):
    print("This is feature 3 of class B")
  def feature4(self):
    print("This is feature 4 of class B")

class C(B): # multi-level inheritance
  def feature5(self):
    print("This is feature 5 of class C")
  def feature6(self):
    print("This is feature 6 of class C")

if __name__ == "__main__":
  a = A()
  b = B()
  c = C()

  print(f"{"*"*40}Using class A{"*"*40}")
  a.feature1()
  a.feature2()

  print(f"{"*"*40}Using class B{"*"*40}")
  b.feature1()
  b.feature2()
  b.feature3()
  b.feature4()

  print(f"{"*"*40}Using class C{"*"*40}")
  c.feature5()
  c.feature4()
  c.feature1()

****************************************Using class A****************************************
This is feature 1 of class A
This is feature 2 of class A
****************************************Using class B****************************************
This is feature 1 of class A
This is feature 2 of class A
This is feature 3 of class B
This is feature 4 of class B
****************************************Using class C****************************************
This is feature 5 of class C
This is feature 4 of class B
This is feature 1 of class A

In [4]:
"""
Why use Numpy ?
Numpy provides a more efficient storage compared to the other data structures. It uses less memory to store data
It performs fast mathematical operations
"""

import numpy as np
myArr = np.array([1,2.87,'IDEAS-TIH'])
print(myArr, type(myArr))
print(myArr[2])
print(myArr.dtype)

myArr_new = np.array([1,2.87,60,8.765432 ], np.int32)
print(myArr_new, type(myArr_new), myArr_new.dtype)
print(f"The shape of the array = {myArr_new.shape}")

['1' '2.87' 'IDEAS-TIH'] <class 'numpy.ndarray'>
IDEAS-TIH
<U32
[ 1  2 60  8] <class 'numpy.ndarray'> int32
The shape of the array = (4,)

In [5]:
myArr_2D=np.array([[3,4,5,6],[7,6,5,4]])
print(myArr_2D, type(myArr_2D), myArr_2D.dtype)
print(f"The shape of the array = {myArr_2D.shape}")

[[3 4 5 6]
 [7 6 5 4]] <class 'numpy.ndarray'> int64
The shape of the array = (2, 4)

In [6]:
# Array Creation : Conversion from other python data structures, namely lists
myList = [[1, 'harry', 3,8],[5,85,7,8],[9.67, 2, 125.578, 8, ]]
listArray = np.array(myList) # converting lists to arrays explicitly
print(listArray, type(listArray), listArray.dtype)
print(listArray.shape[0])
print(listArray.shape[1])
print(listArray.size)
print(listArray[2,1])

[['1' 'harry' '3' '8']
 ['5' '85' '7' '8']
 ['9.67' '2' '125.578' '8']] <class 'numpy.ndarray'> <U32
3
4
12
2

In [7]:
zero_arrays = np.zeros((2,5))
print(zero_arrays, type(zero_arrays), zero_arrays.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] <class 'numpy.ndarray'> float64

In [8]:
rng = np.arange(15) # arange(x) generates an array of length x having elements from 0 to x-1
print(rng, rng.shape)
print("*"*80)
reshape_rng = rng.reshape(3,5)
print(reshape_rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] (15,)
********************************************************************************
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

In [9]:
lspace = np.linspace(1,5, 10) # linspace(x,y,z) : returns an array of length z that has z equally spaced numbers from x to y
print(lspace)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]

In [10]:
# empty arrays:
empArr = np.empty((4,6)) # CREATE A 4X6 EMPTY MATRIX
print(empArr, type(empArr), empArr.dtype)

[[-0.25 -0.5   0.   -0.25  0.25 -0.5 ]
 [ 0.5  -0.25  0.25  0.    0.5   0.25]
 [ 0.25  0.5   0.    0.25 -0.25  0.5 ]
 [-0.5   0.25 -0.25  0.   -0.5  -0.25]] <class 'numpy.ndarray'> float64

In [11]:
empArr_like = np.empty_like(zero_arrays)
print(empArr_like, empArr_like.shape)

[[1.         1.44444444 1.88888889 2.33333333 2.77777778]
 [3.22222222 3.66666667 4.11111111 4.55555556 5.        ]] (2, 5)

In [12]:
ide = np.identity(5)
print(ide, ide.size, ide.shape)
print(np.linalg.det(ide)) # linalg.det()is used to calculate the determinant of a matrix

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 25 (5, 5)
1.0

In [13]:
'''
1D - [Axis 0]
2D - [Axis 0 (Row), Axis 1 (Column)]
'''


X = [[1,2,3], [4,5,6], [7,8,9]]
arr=np.array(X)
print(arr, arr.shape)
print(f"Summation of rows = {arr.sum(axis=0)}") # column is constant, addition occurs between different row elements
print(f"Summation of columns = {arr.sum(axis=1)}") # row is constant, addition occurs between different column elements
print(f"Transpose of a matrix = \n{arr.T}")
print(f"Sum of all the elements of a single row = {arr[2].sum()}")
print(f"Sum of all the elements of a single column = {arr[:,2].sum()}")
print(f"Trace of the matrix (summation of the primary diagonal elements) = {np.trace(X)}")
print(f"Determinant of the matrix = {np.linalg.det(X)}")

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
Summation of rows = [12 15 18]
Summation of columns = [ 6 15 24]
Transpose of a matrix =
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum of all the elements of a single row = 24
Sum of all the elements of a single column = 18
Trace of the matrix (summation of the primary diagonal elements) = 15
Determinant of the matrix = 0.0

In [14]:
arr_flat = arr.flatten()
print("The flattened version of the matrix  =", arr_flat)
print(arr.ravel())

The flattened version of the matrix  = [1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]

In [15]:
one = np.array([1,64,4,634, 2])
print(f"Index that contains the maximum-valued element = {one.argmax()}")
print(f"Index that contains the minimum-valued element = {one.argmin()}")
print(f"Sorted array = {np.sort(one)}")
print(f"{np.argsort(one)}")

Index that contains the maximum-valued element = 3
Index that contains the minimum-valued element = 0
Sorted array = [  1   2   4  64 634]
[0 4 2 1 3]

In [16]:
arr = np.array([[1,2,3], [4,5,6], [7,1,0]])
print(arr)
print("*"*80)
print(arr.argmin()) # return the index where the lowest element is located
print(arr.argmax()) # return the index where the highest element is located
print("*"*80)
print(arr.argmax(axis=0))
print(arr.argmax(axis=1))
print("*"*80)
print(arr.argmin(axis=0))
print(arr.argmin(axis=1))

[[1 2 3]
 [4 5 6]
 [7 1 0]]
********************************************************************************
8
6
********************************************************************************
[2 1 1]
[2 2 0]
********************************************************************************
[0 2 2]
[0 0 2]

In [17]:
print("*"*40+"Arr1"+"*"*40)
ar1 = arr.copy()
print(ar1)
print("*"*40+"Arr2"+"*"*40)
ar2 = np.array([[1,2,1], [4,0,6], [8,1,0]])
print(ar2)
print("*"*40+"Matrix Addition"+"*"*40)
print(ar1+ar2)
print("*"*40+"Matrix dot product"+"*"*40)
print(ar1*ar2)
print("*"*40+"Matrix Multiplication"+"*"*40)
print(np.matmul(ar1,ar2))
print("*"*40+"MAtrix Inverse"+"*"*40)
print(np.linalg.inv(ar2))

****************************************Arr1****************************************
[[1 2 3]
 [4 5 6]
 [7 1 0]]
****************************************Arr2****************************************
[[1 2 1]
 [4 0 6]
 [8 1 0]]
****************************************Matrix Addition****************************************
[[ 2  4  4]
 [ 8  5 12]
 [15  2  0]]
****************************************Matrix dot product****************************************
[[ 1  4  3]
 [16  0 36]
 [56  1  0]]
****************************************Matrix Multiplication****************************************
[[33  5 13]
 [72 14 34]
 [11 14 13]]
****************************************MAtrix Inverse****************************************
[[-0.06382979  0.0106383   0.12765957]
 [ 0.5106383  -0.08510638 -0.0212766 ]
 [ 0.04255319  0.15957447 -0.08510638]]

In [18]:
# Pandas :
import pandas as pd

In [19]:
myDictionary = {
    "name": ["steve", 'tony', 'peter', 'natasha', 'wanda'],
    "marks": [80, 96, 95, 87, 80],
    "city": ["queens", "new_york", "brooklyn", "volgograd", "sokovia"]

}
print(myDictionary)
df = pd.DataFrame(myDictionary)
print(df)
df.to_csv('avengers.csv')

{'name': ['steve', 'tony', 'peter', 'natasha', 'wanda'], 'marks': [80, 96, 95, 87, 80], 'city': ['queens', 'new_york', 'brooklyn', 'volgograd', 'sokovia']}
      name  marks       city
0    steve     80     queens
1     tony     96   new_york
2    peter     95   brooklyn
3  natasha     87  volgograd
4    wanda     80    sokovia

In [20]:
mycsv = pd.read_csv('avengers.csv')
print("*"*90)
print(mycsv, type(mycsv))
print("*"*90)
print(mycsv['name'])

******************************************************************************************
   Unnamed: 0     name  marks       city
0           0    steve     80     queens
1           1     tony     96   new_york
2           2    peter     95   brooklyn
3           3  natasha     87  volgograd
4           4    wanda     80    sokovia <class 'pandas.core.frame.DataFrame'>
******************************************************************************************
0      steve
1       tony
2      peter
3    natasha
4      wanda
Name: name, dtype: object

In [21]:
mycsv['marks'][2] = 99
print(mycsv)

   Unnamed: 0     name  marks       city
0           0    steve     80     queens
1           1     tony     96   new_york
2           2    peter     99   brooklyn
3           3  natasha     87  volgograd
4           4    wanda     80    sokovia

/tmp/ipykernel_34086/1910506485.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  mycsv['marks'][2] = 99
/tmp/ipykernel_34086/1910506485.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mycsv['marks'][2] = 99

In [22]:
df.head(3) # view first few rows of a dataframe by default it show for the first 5

    name  marks      city
0  steve     80    queens
1   tony     96  new_york
2  peter     95  brooklyn

In [23]:
df.tail(3) # view last few rows of a dataframe by default it show for the last 5

      name  marks       city
2    peter     95   brooklyn
3  natasha     87  volgograd
4    wanda     80    sokovia

In [24]:
new_df = pd.DataFrame(np.random.rand(334,5), index = np.arange(334))
print(new_df)

            0         1         2         3         4
0    0.565871  0.072037  0.331380  0.348658  0.233459
1    0.688182  0.586374  0.335176  0.112725  0.388190
2    0.271769  0.037551  0.424272  0.799062  0.190484
3    0.177546  0.750148  0.203852  0.783497  0.470838
4    0.751185  0.309489  0.086412  0.941537  0.051171
..        ...       ...       ...       ...       ...
329  0.542077  0.225047  0.157834  0.022127  0.745757
330  0.366934  0.756213  0.751136  0.476631  0.401673
331  0.057575  0.573009  0.954018  0.430559  0.381172
332  0.908341  0.055465  0.978386  0.456115  0.785134
333  0.976718  0.669172  0.828750  0.284790  0.038081

[334 rows x 5 columns]

In [25]:
new_df.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.497739    0.506928    0.495194    0.493548    0.495437
std      0.301780    0.295291    0.297615    0.285596    0.281398
min      0.000572    0.003316    0.002151    0.001110    0.009407
25%      0.231976    0.231076    0.228486    0.252971    0.260521
50%      0.498659    0.514990    0.481700    0.478450    0.484782
75%      0.764127    0.754411    0.775573    0.750283    0.742757
max      0.992581    0.997129    0.998756    0.997784    0.995169

In [26]:
new_df_np=new_df.to_numpy()

In [27]:
print(type(new_df_np))

<class 'numpy.ndarray'>

In [28]:
new_df.sort_index(axis =0, ascending = False)

            0         1         2         3         4
333  0.976718  0.669172  0.828750  0.284790  0.038081
332  0.908341  0.055465  0.978386  0.456115  0.785134
331  0.057575  0.573009  0.954018  0.430559  0.381172
330  0.366934  0.756213  0.751136  0.476631  0.401673
329  0.542077  0.225047  0.157834  0.022127  0.745757
..        ...       ...       ...       ...       ...
4    0.751185  0.309489  0.086412  0.941537  0.051171
3    0.177546  0.750148  0.203852  0.783497  0.470838
2    0.271769  0.037551  0.424272  0.799062  0.190484
1    0.688182  0.586374  0.335176  0.112725  0.388190
0    0.565871  0.072037  0.331380  0.348658  0.233459

[334 rows x 5 columns]

In [29]:
new_df.head()

          0         1         2         3         4
0  0.565871  0.072037  0.331380  0.348658  0.233459
1  0.688182  0.586374  0.335176  0.112725  0.388190
2  0.271769  0.037551  0.424272  0.799062  0.190484
3  0.177546  0.750148  0.203852  0.783497  0.470838
4  0.751185  0.309489  0.086412  0.941537  0.051171

In [30]:
new_df2 = new_df.copy()
new_df2[3][1] = 7865 # change the value of row 1, column 3
print(new_df2)

            0         1         2            3         4
0    0.565871  0.072037  0.331380     0.348658  0.233459
1    0.688182  0.586374  0.335176  7865.000000  0.388190
2    0.271769  0.037551  0.424272     0.799062  0.190484
3    0.177546  0.750148  0.203852     0.783497  0.470838
4    0.751185  0.309489  0.086412     0.941537  0.051171
..        ...       ...       ...          ...       ...
329  0.542077  0.225047  0.157834     0.022127  0.745757
330  0.366934  0.756213  0.751136     0.476631  0.401673
331  0.057575  0.573009  0.954018     0.430559  0.381172
332  0.908341  0.055465  0.978386     0.456115  0.785134
333  0.976718  0.669172  0.828750     0.284790  0.038081

[334 rows x 5 columns]

/tmp/ipykernel_34086/2608711368.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  new_df2[3][1] = 7865 # change the value of row 1, column 3

In [31]:
print(new_df.loc[1:3]) #view the df from row =1 to row =3

          0         1         2         3         4
1  0.688182  0.586374  0.335176  0.112725  0.388190
2  0.271769  0.037551  0.424272  0.799062  0.190484
3  0.177546  0.750148  0.203852  0.783497  0.470838

In [32]:
new_df.loc[0,4] = 664 # locate the element at 0th row and 4th column and change its value
new_df.head()

          0         1         2         3           4
0  0.565871  0.072037  0.331380  0.348658  664.000000
1  0.688182  0.586374  0.335176  0.112725    0.388190
2  0.271769  0.037551  0.424272  0.799062    0.190484
3  0.177546  0.750148  0.203852  0.783497    0.470838
4  0.751185  0.309489  0.086412  0.941537    0.051171

In [33]:
new_df.columns = list("ABCDE")
new_df.loc[0, 'D'] = 5 # using loc we access an element using row index and column name
new_df.iloc[0, 1] = 5  # using iloc we access an element using row index and column index
new_df.head()

          A         B         C         D           E
0  0.565871  5.000000  0.331380  5.000000  664.000000
1  0.688182  0.586374  0.335176  0.112725    0.388190
2  0.271769  0.037551  0.424272  0.799062    0.190484
3  0.177546  0.750148  0.203852  0.783497    0.470838
4  0.751185  0.309489  0.086412  0.941537    0.051171

In [34]:
new_df.drop('B', axis=1, inplace = True)
new_df.head()

          A         C         D           E
0  0.565871  0.331380  5.000000  664.000000
1  0.688182  0.335176  0.112725    0.388190
2  0.271769  0.424272  0.799062    0.190484
3  0.177546  0.203852  0.783497    0.470838
4  0.751185  0.086412  0.941537    0.051171

In [37]:
new_df.loc[(new_df['A']<0.3)&(new_df['C']>0.1)]

            A         C         D         E
2    0.271769  0.424272  0.799062  0.190484
3    0.177546  0.203852  0.783497  0.470838
5    0.062985  0.602786  0.646278  0.516496
8    0.046966  0.964393  0.005807  0.262561
12   0.122258  0.399217  0.826801  0.773004
..        ...       ...       ...       ...
307  0.155443  0.229359  0.704295  0.620040
313  0.041813  0.492840  0.100535  0.429108
324  0.255033  0.220628  0.928748  0.657238
326  0.020341  0.998756  0.654961  0.986402
331  0.057575  0.954018  0.430559  0.381172

[96 rows x 4 columns]

In [38]:
#delete a row
new_df.drop(0, axis=0, inplace = True)
new_df.head()

          A         C         D         E
1  0.688182  0.335176  0.112725  0.388190
2  0.271769  0.424272  0.799062  0.190484
3  0.177546  0.203852  0.783497  0.470838
4  0.751185  0.086412  0.941537  0.051171
5  0.062985  0.602786  0.646278  0.516496

In [39]:
new_df.reset_index(drop=True, inplace=True)
new_df.head()

          A         C         D         E
0  0.688182  0.335176  0.112725  0.388190
1  0.271769  0.424272  0.799062  0.190484
2  0.177546  0.203852  0.783497  0.470838
3  0.751185  0.086412  0.941537  0.051171
4  0.062985  0.602786  0.646278  0.516496